language: python
python:
  - "3.6"
env:
  - HYPOTHESIS_PROFILE=ci
install: "pip install -r requirements.txt"
script: "python3 -m unittest discover --verbose --top-level-directory bogo --start-directory tests"
