language: python
python:
  - "3.6"
git:
  depth: 1
env:
  - HYPOTHESIS_PROFILE=ci
install: "pip install -r requirements.txt"
script:
  - "cd bogo"
  - "python3 -m doctest --verbose bogoapp/tools.py"
  - "python3 -m unittest discover --verbose --top-level-directory . --start-directory tests"
