language: python
python:
  - "3.6"
git:
  depth: 1
env:
  - PYTHONPATH="bogo:bogo/bogoapp"
  - HYPOTHESIS_PROFILE=ci
install: "pip install -r requirements.txt"
script:
  - "python3 -m doctest --verbose tools.py"
  - "python3 -m unittest discover --verbose --start-directory tests"
