
BROKER_URL = 'amqp://guest:guest@localhost:5672//'

REDIS_PORT = '6379'
REDIS_DECODE_RESPONSES = True

DATABASE_NAME = 'app.db'
SCHEMA_NAME = "schema.sql"
RANDOM_SEED = 42
BACKUP_INTERVAL = 10**9
SEQUENCE_MAX_LENGTH = 30
SEQUENCE_STEP = 10
ITER_SPEED_RESOLUTION = 500

APP_CONTEXT_DATABASE_NAME = "_" + DATABASE_NAME.replace(".", "_")


