
REDIS_PORT = '6379'
REDIS_DECODE_RESPONSES = True
BROKER_URL = 'redis://localhost:{}/0'.format(REDIS_PORT)

TEMPLATES_AUTO_RELOAD = True

DATABASE_NAME = 'app.db'
SCHEMA_NAME = "schema.sql"
APP_CONTEXT_DATABASE_NAME = "_" + DATABASE_NAME.replace(".", "_")

RANDOM_SEED = 42
SEQUENCE_MAX_LENGTH = 14
SEQUENCE_MIN_LENGTH = 9
ITER_SPEED_CACHE_EXPIRE_SECONDS = 3

DUMMY_SORT_COLUMN_COUNT = 10000

WORKER_LOGGER_PATH = '/var/log/not-enough-bogo/worker.log'

