
BROKER_URL = 'redis://localhost:6379/0'

REDIS_PORT = '6379'
REDIS_DECODE_RESPONSES = True

DATABASE_NAME = 'app.db'
SCHEMA_NAME = "schema.sql"
RANDOM_SEED = 42
BACKUP_INTERVAL = 10**11 # About once a week
SEQUENCE_MAX_LENGTH = 14
SEQUENCE_MIN_LENGTH = 9
ITER_SPEED_RESOLUTION = 500

TEMPLATES_AUTO_RELOAD = True

APP_CONTEXT_DATABASE_NAME = "_" + DATABASE_NAME.replace(".", "_")


